apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fabric-dhcpd.fullname" . }}
  labels:
    {{- include "fabric-dhcpd.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - dhcp.githedgehog.com
  resources:
  - dhcpsubnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.githedgehog.com
  resources:
  - dhcpsubnets/status
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
