# permissions for end users to edit fabrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fabric-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fabric
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
  name: fabric-editor-role
rules:
- apiGroups:
  - fabric.githedgehog.com
  resources:
  - fabrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fabric.githedgehog.com
  resources:
  - fabrics/status
  verbs:
  - get
