//go:build !ignore_autogenerated

// Copyright 2026 Hedgehog
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricController) DeepCopyInto(out *FabricController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricController.
func (in *FabricController) DeepCopy() *FabricController {
	if in == nil {
		return nil
	}
	out := new(FabricController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricControllerList) DeepCopyInto(out *FabricControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricControllerList.
func (in *FabricControllerList) DeepCopy() *FabricControllerList {
	if in == nil {
		return nil
	}
	out := new(FabricControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricControllerRefresh) DeepCopyInto(out *FabricControllerRefresh) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]FabricControllerRefreshKind, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricControllerRefresh.
func (in *FabricControllerRefresh) DeepCopy() *FabricControllerRefresh {
	if in == nil {
		return nil
	}
	out := new(FabricControllerRefresh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricControllerRefreshKind) DeepCopyInto(out *FabricControllerRefreshKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricControllerRefreshKind.
func (in *FabricControllerRefreshKind) DeepCopy() *FabricControllerRefreshKind {
	if in == nil {
		return nil
	}
	out := new(FabricControllerRefreshKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricControllerSpec) DeepCopyInto(out *FabricControllerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricControllerSpec.
func (in *FabricControllerSpec) DeepCopy() *FabricControllerSpec {
	if in == nil {
		return nil
	}
	out := new(FabricControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricControllerStatus) DeepCopyInto(out *FabricControllerStatus) {
	*out = *in
	in.Refresh.DeepCopyInto(&out.Refresh)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricControllerStatus.
func (in *FabricControllerStatus) DeepCopy() *FabricControllerStatus {
	if in == nil {
		return nil
	}
	out := new(FabricControllerStatus)
	in.DeepCopyInto(out)
	return out
}
