//go:build !ignore_autogenerated

// Copyright 2023 Hedgehog
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	vpcv1beta1 "go.githedgehog.com/fabric/api/vpc/v1beta1"
	wiringv1beta1 "go.githedgehog.com/fabric/api/wiring/v1beta1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Alloy.DeepCopyInto(&out.Alloy)
	out.Version = in.Version
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]UserCreds, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Switch.DeepCopyInto(&out.Switch)
	if in.SwitchProfile != nil {
		in, out := &in.SwitchProfile, &out.SwitchProfile
		*out = new(wiringv1beta1.SwitchProfileSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Switches != nil {
		in, out := &in.Switches, &out.Switches
		*out = make(map[string]wiringv1beta1.SwitchSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.RedundancyGroupPeers != nil {
		in, out := &in.RedundancyGroupPeers, &out.RedundancyGroupPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make(map[string]wiringv1beta1.ConnectionSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make(map[string]vpcv1beta1.VPCSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.VPCAttachments != nil {
		in, out := &in.VPCAttachments, &out.VPCAttachments
		*out = make(map[string]vpcv1beta1.VPCAttachmentSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VPCPeerings != nil {
		in, out := &in.VPCPeerings, &out.VPCPeerings
		*out = make(map[string]vpcv1beta1.VPCPeeringSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.IPv4Namespaces != nil {
		in, out := &in.IPv4Namespaces, &out.IPv4Namespaces
		*out = make(map[string]vpcv1beta1.IPv4NamespaceSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.VLANNamespaces != nil {
		in, out := &in.VLANNamespaces, &out.VLANNamespaces
		*out = make(map[string]wiringv1beta1.VLANNamespaceSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Externals != nil {
		in, out := &in.Externals, &out.Externals
		*out = make(map[string]vpcv1beta1.ExternalSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExternalAttachments != nil {
		in, out := &in.ExternalAttachments, &out.ExternalAttachments
		*out = make(map[string]vpcv1beta1.ExternalAttachmentSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExternalPeerings != nil {
		in, out := &in.ExternalPeerings, &out.ExternalPeerings
		*out = make(map[string]vpcv1beta1.ExternalPeeringSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ConfiguredVPCSubnets != nil {
		in, out := &in.ConfiguredVPCSubnets, &out.ConfiguredVPCSubnets
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AttachedVPCs != nil {
		in, out := &in.AttachedVPCs, &out.AttachedVPCs
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Catalog.DeepCopyInto(&out.Catalog)
	if in.StatusUpdates != nil {
		in, out := &in.StatusUpdates, &out.StatusUpdates
		*out = make([]ApplyStatusUpdate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpecConfig) DeepCopyInto(out *AgentSpecConfig) {
	*out = *in
	if in.SpineLeaf != nil {
		in, out := &in.SpineLeaf, &out.SpineLeaf
		*out = new(AgentSpecConfigSpineLeaf)
		**out = **in
	}
	in.Alloy.DeepCopyInto(&out.Alloy)
	if in.GatewayCommunities != nil {
		in, out := &in.GatewayCommunities, &out.GatewayCommunities
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpecConfig.
func (in *AgentSpecConfig) DeepCopy() *AgentSpecConfig {
	if in == nil {
		return nil
	}
	out := new(AgentSpecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpecConfigSpineLeaf) DeepCopyInto(out *AgentSpecConfigSpineLeaf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpecConfigSpineLeaf.
func (in *AgentSpecConfigSpineLeaf) DeepCopy() *AgentSpecConfigSpineLeaf {
	if in == nil {
		return nil
	}
	out := new(AgentSpecConfigSpineLeaf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	in.LastHeartbeat.DeepCopyInto(&out.LastHeartbeat)
	in.LastAttemptTime.DeepCopyInto(&out.LastAttemptTime)
	in.LastAppliedTime.DeepCopyInto(&out.LastAppliedTime)
	in.State.DeepCopyInto(&out.State)
	if in.StatusUpdates != nil {
		in, out := &in.StatusUpdates, &out.StatusUpdates
		*out = make([]ApplyStatusUpdate, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentVersion) DeepCopyInto(out *AgentVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentVersion.
func (in *AgentVersion) DeepCopy() *AgentVersion {
	if in == nil {
		return nil
	}
	out := new(AgentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyStatusUpdate) DeepCopyInto(out *ApplyStatusUpdate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyStatusUpdate.
func (in *ApplyStatusUpdate) DeepCopy() *ApplyStatusUpdate {
	if in == nil {
		return nil
	}
	out := new(ApplyStatusUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPMessages) DeepCopyInto(out *BGPMessages) {
	*out = *in
	out.Received = in.Received
	out.Sent = in.Sent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPMessages.
func (in *BGPMessages) DeepCopy() *BGPMessages {
	if in == nil {
		return nil
	}
	out := new(BGPMessages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPMessagesCounters) DeepCopyInto(out *BGPMessagesCounters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPMessagesCounters.
func (in *BGPMessagesCounters) DeepCopy() *BGPMessagesCounters {
	if in == nil {
		return nil
	}
	out := new(BGPMessagesCounters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Catalog) DeepCopyInto(out *Catalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Catalog.
func (in *Catalog) DeepCopy() *Catalog {
	if in == nil {
		return nil
	}
	out := new(Catalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Catalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogList) DeepCopyInto(out *CatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Catalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogList.
func (in *CatalogList) DeepCopy() *CatalogList {
	if in == nil {
		return nil
	}
	out := new(CatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogSpec) DeepCopyInto(out *CatalogSpec) {
	*out = *in
	if in.ConnectionIDs != nil {
		in, out := &in.ConnectionIDs, &out.ConnectionIDs
		*out = make(map[string]uint32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VPCVNIs != nil {
		in, out := &in.VPCVNIs, &out.VPCVNIs
		*out = make(map[string]uint32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VPCSubnetVNIs != nil {
		in, out := &in.VPCSubnetVNIs, &out.VPCSubnetVNIs
		*out = make(map[string]map[string]uint32, len(*in))
		for key, val := range *in {
			var outVal map[string]uint32
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]uint32, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.IRBVLANs != nil {
		in, out := &in.IRBVLANs, &out.IRBVLANs
		*out = make(map[string]uint16, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PortChannelIDs != nil {
		in, out := &in.PortChannelIDs, &out.PortChannelIDs
		*out = make(map[string]uint16, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LooopbackWorkaroundLinks != nil {
		in, out := &in.LooopbackWorkaroundLinks, &out.LooopbackWorkaroundLinks
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoopbackWorkaroundVLANs != nil {
		in, out := &in.LoopbackWorkaroundVLANs, &out.LoopbackWorkaroundVLANs
		*out = make(map[string]uint16, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TH5WorkaroundVLANs != nil {
		in, out := &in.TH5WorkaroundVLANs, &out.TH5WorkaroundVLANs
		*out = make(map[string]uint16, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalIDs != nil {
		in, out := &in.ExternalIDs, &out.ExternalIDs
		*out = make(map[string]uint16, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make(map[string]uint32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogSpec.
func (in *CatalogSpec) DeepCopy() *CatalogSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogStatus) DeepCopyInto(out *CatalogStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogStatus.
func (in *CatalogStatus) DeepCopy() *CatalogStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchState) DeepCopyInto(out *SwitchState) {
	*out = *in
	out.NOS = in.NOS
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(map[string]SwitchStateInterface, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Breakouts != nil {
		in, out := &in.Breakouts, &out.Breakouts
		*out = make(map[string]SwitchStateBreakout, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Transceivers != nil {
		in, out := &in.Transceivers, &out.Transceivers
		*out = make(map[string]SwitchStateTransceiver, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.BGPNeighbors != nil {
		in, out := &in.BGPNeighbors, &out.BGPNeighbors
		*out = make(map[string]map[string]SwitchStateBGPNeighbor, len(*in))
		for key, val := range *in {
			var outVal map[string]SwitchStateBGPNeighbor
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]SwitchStateBGPNeighbor, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
	in.Platform.DeepCopyInto(&out.Platform)
	out.CriticalResources = in.CriticalResources
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchState.
func (in *SwitchState) DeepCopy() *SwitchState {
	if in == nil {
		return nil
	}
	out := new(SwitchState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateBGPNeighbor) DeepCopyInto(out *SwitchStateBGPNeighbor) {
	*out = *in
	in.LastEstablished.DeepCopyInto(&out.LastEstablished)
	in.LastRead.DeepCopyInto(&out.LastRead)
	in.LastResetTime.DeepCopyInto(&out.LastResetTime)
	in.LastWrite.DeepCopyInto(&out.LastWrite)
	out.Messages = in.Messages
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make(map[string]SwitchStateBGPNeighborPrefixes, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateBGPNeighbor.
func (in *SwitchStateBGPNeighbor) DeepCopy() *SwitchStateBGPNeighbor {
	if in == nil {
		return nil
	}
	out := new(SwitchStateBGPNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateBGPNeighborPrefixes) DeepCopyInto(out *SwitchStateBGPNeighborPrefixes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateBGPNeighborPrefixes.
func (in *SwitchStateBGPNeighborPrefixes) DeepCopy() *SwitchStateBGPNeighborPrefixes {
	if in == nil {
		return nil
	}
	out := new(SwitchStateBGPNeighborPrefixes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateBreakout) DeepCopyInto(out *SwitchStateBreakout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateBreakout.
func (in *SwitchStateBreakout) DeepCopy() *SwitchStateBreakout {
	if in == nil {
		return nil
	}
	out := new(SwitchStateBreakout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateCRM) DeepCopyInto(out *SwitchStateCRM) {
	*out = *in
	out.ACLStats = in.ACLStats
	out.Stats = in.Stats
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateCRM.
func (in *SwitchStateCRM) DeepCopy() *SwitchStateCRM {
	if in == nil {
		return nil
	}
	out := new(SwitchStateCRM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateCRMACLDetails) DeepCopyInto(out *SwitchStateCRMACLDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateCRMACLDetails.
func (in *SwitchStateCRMACLDetails) DeepCopy() *SwitchStateCRMACLDetails {
	if in == nil {
		return nil
	}
	out := new(SwitchStateCRMACLDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateCRMACLInfo) DeepCopyInto(out *SwitchStateCRMACLInfo) {
	*out = *in
	out.Lag = in.Lag
	out.Port = in.Port
	out.RIF = in.RIF
	out.Switch = in.Switch
	out.VLAN = in.VLAN
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateCRMACLInfo.
func (in *SwitchStateCRMACLInfo) DeepCopy() *SwitchStateCRMACLInfo {
	if in == nil {
		return nil
	}
	out := new(SwitchStateCRMACLInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateCRMACLStats) DeepCopyInto(out *SwitchStateCRMACLStats) {
	*out = *in
	out.Egress = in.Egress
	out.Ingress = in.Ingress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateCRMACLStats.
func (in *SwitchStateCRMACLStats) DeepCopy() *SwitchStateCRMACLStats {
	if in == nil {
		return nil
	}
	out := new(SwitchStateCRMACLStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateCRMStats) DeepCopyInto(out *SwitchStateCRMStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateCRMStats.
func (in *SwitchStateCRMStats) DeepCopy() *SwitchStateCRMStats {
	if in == nil {
		return nil
	}
	out := new(SwitchStateCRMStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateInterface) DeepCopyInto(out *SwitchStateInterface) {
	*out = *in
	in.LastChange.DeepCopyInto(&out.LastChange)
	if in.Counters != nil {
		in, out := &in.Counters, &out.Counters
		*out = new(SwitchStateInterfaceCounters)
		(*in).DeepCopyInto(*out)
	}
	if in.LLDPNeighbors != nil {
		in, out := &in.LLDPNeighbors, &out.LLDPNeighbors
		*out = make([]SwitchStateLLDPNeighbor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateInterface.
func (in *SwitchStateInterface) DeepCopy() *SwitchStateInterface {
	if in == nil {
		return nil
	}
	out := new(SwitchStateInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateInterfaceCounters) DeepCopyInto(out *SwitchStateInterfaceCounters) {
	*out = *in
	in.LastClear.DeepCopyInto(&out.LastClear)
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make(map[string]SwitchStateInterfaceCountersQueue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateInterfaceCounters.
func (in *SwitchStateInterfaceCounters) DeepCopy() *SwitchStateInterfaceCounters {
	if in == nil {
		return nil
	}
	out := new(SwitchStateInterfaceCounters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateInterfaceCountersQueue) DeepCopyInto(out *SwitchStateInterfaceCountersQueue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateInterfaceCountersQueue.
func (in *SwitchStateInterfaceCountersQueue) DeepCopy() *SwitchStateInterfaceCountersQueue {
	if in == nil {
		return nil
	}
	out := new(SwitchStateInterfaceCountersQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateLLDPNeighbor) DeepCopyInto(out *SwitchStateLLDPNeighbor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateLLDPNeighbor.
func (in *SwitchStateLLDPNeighbor) DeepCopy() *SwitchStateLLDPNeighbor {
	if in == nil {
		return nil
	}
	out := new(SwitchStateLLDPNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateNOS) DeepCopyInto(out *SwitchStateNOS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateNOS.
func (in *SwitchStateNOS) DeepCopy() *SwitchStateNOS {
	if in == nil {
		return nil
	}
	out := new(SwitchStateNOS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStatePlatform) DeepCopyInto(out *SwitchStatePlatform) {
	*out = *in
	if in.Fans != nil {
		in, out := &in.Fans, &out.Fans
		*out = make(map[string]SwitchStatePlatformFan, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PSUs != nil {
		in, out := &in.PSUs, &out.PSUs
		*out = make(map[string]SwitchStatePlatformPSU, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Temperatures != nil {
		in, out := &in.Temperatures, &out.Temperatures
		*out = make(map[string]SwitchStatePlatformTemperature, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStatePlatform.
func (in *SwitchStatePlatform) DeepCopy() *SwitchStatePlatform {
	if in == nil {
		return nil
	}
	out := new(SwitchStatePlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStatePlatformFan) DeepCopyInto(out *SwitchStatePlatformFan) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStatePlatformFan.
func (in *SwitchStatePlatformFan) DeepCopy() *SwitchStatePlatformFan {
	if in == nil {
		return nil
	}
	out := new(SwitchStatePlatformFan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStatePlatformPSU) DeepCopyInto(out *SwitchStatePlatformPSU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStatePlatformPSU.
func (in *SwitchStatePlatformPSU) DeepCopy() *SwitchStatePlatformPSU {
	if in == nil {
		return nil
	}
	out := new(SwitchStatePlatformPSU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStatePlatformTemperature) DeepCopyInto(out *SwitchStatePlatformTemperature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStatePlatformTemperature.
func (in *SwitchStatePlatformTemperature) DeepCopy() *SwitchStatePlatformTemperature {
	if in == nil {
		return nil
	}
	out := new(SwitchStatePlatformTemperature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateTransceiver) DeepCopyInto(out *SwitchStateTransceiver) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make(map[string]SwitchStateTransceiverChannel, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateTransceiver.
func (in *SwitchStateTransceiver) DeepCopy() *SwitchStateTransceiver {
	if in == nil {
		return nil
	}
	out := new(SwitchStateTransceiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchStateTransceiverChannel) DeepCopyInto(out *SwitchStateTransceiverChannel) {
	*out = *in
	if in.In != nil {
		in, out := &in.In, &out.In
		*out = new(float64)
		**out = **in
	}
	if in.Out != nil {
		in, out := &in.Out, &out.Out
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchStateTransceiverChannel.
func (in *SwitchStateTransceiverChannel) DeepCopy() *SwitchStateTransceiverChannel {
	if in == nil {
		return nil
	}
	out := new(SwitchStateTransceiverChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCreds) DeepCopyInto(out *UserCreds) {
	*out = *in
	if in.SSHKeys != nil {
		in, out := &in.SSHKeys, &out.SSHKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCreds.
func (in *UserCreds) DeepCopy() *UserCreds {
	if in == nil {
		return nil
	}
	out := new(UserCreds)
	in.DeepCopyInto(out)
	return out
}
