//go:build !ignore_autogenerated

// Copyright 2023 Hedgehog
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package meta

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlloyConfig) DeepCopyInto(out *AlloyConfig) {
	*out = *in
	if in.UnixExporterCollectors != nil {
		in, out := &in.UnixExporterCollectors, &out.UnixExporterCollectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrometheusTargets != nil {
		in, out := &in.PrometheusTargets, &out.PrometheusTargets
		*out = make(map[string]AlloyPrometheusTarget, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.LokiTargets != nil {
		in, out := &in.LokiTargets, &out.LokiTargets
		*out = make(map[string]AlloyLokiTarget, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlloyConfig.
func (in *AlloyConfig) DeepCopy() *AlloyConfig {
	if in == nil {
		return nil
	}
	out := new(AlloyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlloyLokiTarget) DeepCopyInto(out *AlloyLokiTarget) {
	*out = *in
	in.AlloyTarget.DeepCopyInto(&out.AlloyTarget)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlloyLokiTarget.
func (in *AlloyLokiTarget) DeepCopy() *AlloyLokiTarget {
	if in == nil {
		return nil
	}
	out := new(AlloyLokiTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlloyPrometheusTarget) DeepCopyInto(out *AlloyPrometheusTarget) {
	*out = *in
	in.AlloyTarget.DeepCopyInto(&out.AlloyTarget)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlloyPrometheusTarget.
func (in *AlloyPrometheusTarget) DeepCopy() *AlloyPrometheusTarget {
	if in == nil {
		return nil
	}
	out := new(AlloyPrometheusTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlloyTarget) DeepCopyInto(out *AlloyTarget) {
	*out = *in
	out.BasicAuth = in.BasicAuth
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlloyTarget.
func (in *AlloyTarget) DeepCopy() *AlloyTarget {
	if in == nil {
		return nil
	}
	out := new(AlloyTarget)
	in.DeepCopyInto(out)
	return out
}
