// Copyright 2025 Hedgehog
// SPDX-License-Identifier: Apache-2.0

package switchprofile

import (
	"go.githedgehog.com/fabric/api/meta"
	wiringapi "go.githedgehog.com/fabric/api/wiring/v1beta1"
	kmetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var CmlsNvidiaSN5610 = wiringapi.SwitchProfile{
	ObjectMeta: kmetav1.ObjectMeta{
		Name: "nvidia-sn5610",
	},
	Spec: wiringapi.SwitchProfileSpec{
		DisplayName:   "NVIDIA SN5610",
		SwitchSilicon: SiliconSpectrum4,
		Features: wiringapi.SwitchProfileFeatures{
			Subinterfaces: true,
			ACLs:          true,
			L2VNI:         true,
			L3VNI:         true,
			RoCE:          true,
			MCLAG:         false,
			ESLAG:         true,
			ECMPRoCEQPN:   false,
		},
		NOSType:  meta.NOSTypeCumulusVX,
		Platform: "x86_64-nv-sn5610-r0",
		Config:   wiringapi.SwitchProfileConfig{
			// TODO
		},
		Ports: map[string]wiringapi.SwitchProfilePort{
			"M1":    {NOSName: "Management0", Management: true, OniePortName: "eth0"},
			"E1/1":  {NOSName: "1", BaseNOSName: "swp", Label: "1", Profile: "QSFP56-DD", Pipeline: "1"},
			"E1/2":  {NOSName: "2", BaseNOSName: "swp", Label: "2", Profile: "QSFP56-DD", Pipeline: "2"},
			"E1/3":  {NOSName: "3", BaseNOSName: "swp", Label: "3", Profile: "QSFP56-DD", Pipeline: "3"},
			"E1/4":  {NOSName: "4", BaseNOSName: "swp", Label: "4", Profile: "QSFP56-DD", Pipeline: "4"},
			"E1/5":  {NOSName: "5", BaseNOSName: "swp", Label: "5", Profile: "QSFP56-DD", Pipeline: "5"},
			"E1/6":  {NOSName: "6", BaseNOSName: "swp", Label: "6", Profile: "QSFP56-DD", Pipeline: "6"},
			"E1/7":  {NOSName: "7", BaseNOSName: "swp", Label: "7", Profile: "QSFP56-DD", Pipeline: "7"},
			"E1/8":  {NOSName: "8", BaseNOSName: "swp", Label: "8", Profile: "QSFP56-DD", Pipeline: "8"},
			"E1/9":  {NOSName: "9", BaseNOSName: "swp", Label: "9", Profile: "QSFP56-DD", Pipeline: "9"},
			"E1/10": {NOSName: "10", BaseNOSName: "swp", Label: "10", Profile: "QSFP56-DD", Pipeline: "10"},
			"E1/11": {NOSName: "11", BaseNOSName: "swp", Label: "11", Profile: "QSFP56-DD", Pipeline: "11"},
			"E1/12": {NOSName: "12", BaseNOSName: "swp", Label: "12", Profile: "QSFP56-DD", Pipeline: "12"},
			"E1/13": {NOSName: "13", BaseNOSName: "swp", Label: "13", Profile: "QSFP56-DD", Pipeline: "13"},
			"E1/14": {NOSName: "14", BaseNOSName: "swp", Label: "14", Profile: "QSFP56-DD", Pipeline: "14"},
			"E1/15": {NOSName: "15", BaseNOSName: "swp", Label: "15", Profile: "QSFP56-DD", Pipeline: "15"},
			"E1/16": {NOSName: "16", BaseNOSName: "swp", Label: "16", Profile: "QSFP56-DD", Pipeline: "15"},
			"E1/17": {NOSName: "17", BaseNOSName: "swp", Label: "17", Profile: "QSFP56-DD", Pipeline: "17"},
			"E1/18": {NOSName: "18", BaseNOSName: "swp", Label: "18", Profile: "QSFP56-DD", Pipeline: "18"},
			"E1/19": {NOSName: "19", BaseNOSName: "swp", Label: "19", Profile: "QSFP56-DD", Pipeline: "19"},
			"E1/20": {NOSName: "20", BaseNOSName: "swp", Label: "20", Profile: "QSFP56-DD", Pipeline: "20"},
			"E1/21": {NOSName: "21", BaseNOSName: "swp", Label: "21", Profile: "QSFP56-DD", Pipeline: "21"},
			"E1/22": {NOSName: "22", BaseNOSName: "swp", Label: "22", Profile: "QSFP56-DD", Pipeline: "22"},
			"E1/23": {NOSName: "23", BaseNOSName: "swp", Label: "23", Profile: "QSFP56-DD", Pipeline: "23"},
			"E1/24": {NOSName: "24", BaseNOSName: "swp", Label: "24", Profile: "QSFP56-DD", Pipeline: "24"},
			"E1/25": {NOSName: "25", BaseNOSName: "swp", Label: "25", Profile: "QSFP56-DD", Pipeline: "25"},
			"E1/26": {NOSName: "26", BaseNOSName: "swp", Label: "26", Profile: "QSFP56-DD", Pipeline: "25"},
			"E1/27": {NOSName: "27", BaseNOSName: "swp", Label: "27", Profile: "QSFP56-DD", Pipeline: "27"},
			"E1/28": {NOSName: "28", BaseNOSName: "swp", Label: "28", Profile: "QSFP56-DD", Pipeline: "28"},
			"E1/29": {NOSName: "29", BaseNOSName: "swp", Label: "29", Profile: "QSFP56-DD", Pipeline: "29"},
			"E1/30": {NOSName: "30", BaseNOSName: "swp", Label: "30", Profile: "QSFP56-DD", Pipeline: "30"},
			"E1/31": {NOSName: "31", BaseNOSName: "swp", Label: "31", Profile: "QSFP56-DD", Pipeline: "31"},
			"E1/32": {NOSName: "32", BaseNOSName: "swp", Label: "32", Profile: "QSFP56-DD", Pipeline: "32"},
			"E1/33": {NOSName: "33", BaseNOSName: "swp", Label: "33", Profile: "QSFP56-DD", Pipeline: "33"},
			"E1/34": {NOSName: "34", BaseNOSName: "swp", Label: "34", Profile: "QSFP56-DD", Pipeline: "34"},
			"E1/35": {NOSName: "35", BaseNOSName: "swp", Label: "35", Profile: "QSFP56-DD", Pipeline: "35"},
			"E1/36": {NOSName: "36", BaseNOSName: "swp", Label: "36", Profile: "QSFP56-DD", Pipeline: "35"},
			"E1/37": {NOSName: "37", BaseNOSName: "swp", Label: "37", Profile: "QSFP56-DD", Pipeline: "37"},
			"E1/38": {NOSName: "38", BaseNOSName: "swp", Label: "38", Profile: "QSFP56-DD", Pipeline: "38"},
			"E1/39": {NOSName: "39", BaseNOSName: "swp", Label: "39", Profile: "QSFP56-DD", Pipeline: "39"},
			"E1/40": {NOSName: "40", BaseNOSName: "swp", Label: "40", Profile: "QSFP56-DD", Pipeline: "40"},
			"E1/41": {NOSName: "41", BaseNOSName: "swp", Label: "41", Profile: "QSFP56-DD", Pipeline: "41"},
			"E1/42": {NOSName: "42", BaseNOSName: "swp", Label: "42", Profile: "QSFP56-DD", Pipeline: "42"},
			"E1/43": {NOSName: "43", BaseNOSName: "swp", Label: "43", Profile: "QSFP56-DD", Pipeline: "43"},
			"E1/44": {NOSName: "44", BaseNOSName: "swp", Label: "44", Profile: "QSFP56-DD", Pipeline: "44"},
			"E1/45": {NOSName: "45", BaseNOSName: "swp", Label: "45", Profile: "QSFP56-DD", Pipeline: "45"},
			"E1/46": {NOSName: "46", BaseNOSName: "swp", Label: "46", Profile: "QSFP56-DD", Pipeline: "45"},
			"E1/47": {NOSName: "47", BaseNOSName: "swp", Label: "47", Profile: "QSFP56-DD", Pipeline: "47"},
			"E1/48": {NOSName: "48", BaseNOSName: "swp", Label: "48", Profile: "QSFP56-DD", Pipeline: "48"},
			"E1/49": {NOSName: "49", BaseNOSName: "swp", Label: "49", Profile: "QSFP56-DD", Pipeline: "49"},
			"E1/50": {NOSName: "50", BaseNOSName: "swp", Label: "50", Profile: "QSFP56-DD", Pipeline: "50"},
			"E1/51": {NOSName: "51", BaseNOSName: "swp", Label: "51", Profile: "QSFP56-DD", Pipeline: "51"},
			"E1/52": {NOSName: "52", BaseNOSName: "swp", Label: "52", Profile: "QSFP56-DD", Pipeline: "52"},
			"E1/53": {NOSName: "53", BaseNOSName: "swp", Label: "53", Profile: "QSFP56-DD", Pipeline: "53"},
			"E1/54": {NOSName: "54", BaseNOSName: "swp", Label: "54", Profile: "QSFP56-DD", Pipeline: "54"},
			"E1/55": {NOSName: "55", BaseNOSName: "swp", Label: "55", Profile: "QSFP56-DD", Pipeline: "55"},
			"E1/56": {NOSName: "56", BaseNOSName: "swp", Label: "56", Profile: "QSFP56-DD", Pipeline: "55"},
			"E1/57": {NOSName: "57", BaseNOSName: "swp", Label: "57", Profile: "QSFP56-DD", Pipeline: "57"},
			"E1/58": {NOSName: "58", BaseNOSName: "swp", Label: "58", Profile: "QSFP56-DD", Pipeline: "58"},
			"E1/59": {NOSName: "59", BaseNOSName: "swp", Label: "59", Profile: "QSFP56-DD", Pipeline: "59"},
			"E1/60": {NOSName: "60", BaseNOSName: "swp", Label: "60", Profile: "QSFP56-DD", Pipeline: "60"},
			"E1/61": {NOSName: "61", BaseNOSName: "swp", Label: "61", Profile: "QSFP56-DD", Pipeline: "61"},
			"E1/62": {NOSName: "62", BaseNOSName: "swp", Label: "62", Profile: "QSFP56-DD", Pipeline: "62"},
			"E1/63": {NOSName: "63", BaseNOSName: "swp", Label: "63", Profile: "QSFP56-DD", Pipeline: "63"},
			"E1/64": {NOSName: "64", BaseNOSName: "swp", Label: "64", Profile: "QSFP56-DD", Pipeline: "64"},
			"E1/65": {NOSName: "65", BaseNOSName: "swp", Label: "65", Profile: "SFP28"},
			"E1/66": {NOSName: "66", BaseNOSName: "swp", Label: "66", Profile: "SFP28"},
		},
		PortProfiles: map[string]wiringapi.SwitchProfilePortProfile{
			"SFP28-10G": {
				Speed: &wiringapi.SwitchProfilePortProfileSpeed{
					Default:   "10G",
					Supported: []string{"1G", "10G", "25G"},
				},
			},
		},
			"QSFP56-DD": {
				Breakout: &wiringapi.SwitchProfilePortProfileBreakout{
					Default: "1x200G",
					Supported: map[string]wiringapi.SwitchProfilePortProfileBreakoutMode{
						"1x25G":  {Offsets: []string{""}},
						"1x40G":  {Offsets: []string{""}},
						"1x50G":  {Offsets: []string{""}},
						"1x100G": {Offsets: []string{""}},
						"1x200G": {Offsets: []string{""}},
						"2x25G":  {Offsets: []string{"0", "1"}},
						"2x40G":  {Offsets: []string{"0", "1"}},
						"2x50G":  {Offsets: []string{"0", "1"}},
						"2x100G": {Offsets: []string{"0", "1"}},
						"4x10G":  {Offsets: []string{"0", "1", "2", "3"}},
						"4x40G":  {Offsets: []string{"0", "1", "2", "3"}},
						"4x50G":  {Offsets: []string{"0", "1", "2", "3"}},
						"8x100G":  {Offsets: []string{"0", "1", "2", "3","4","5","6","7"}},
					},
				},
				AutoNegAllowed: true,
				AutoNegDefault: true,
			},
		},
		Pipelines: map[string]wiringapi.SwitchProfilePipeline{
			"1":  {MaxPorts: 8},
			"2":  {MaxPorts: 4},
			"3":  {MaxPorts: 8},
			"4":  {MaxPorts: 4},
			"5":  {MaxPorts: 8},
			"6":  {MaxPorts: 4},
			"7":  {MaxPorts: 8},
			"8":  {MaxPorts: 4},
			"9":  {MaxPorts: 8},
			"10": {MaxPorts: 4},
			"11": {MaxPorts: 8},
			"12": {MaxPorts: 4},
			"13": {MaxPorts: 8},
			"14": {MaxPorts: 4},
			"15": {MaxPorts: 8},
			"16": {MaxPorts: 4},
			"17": {MaxPorts: 8},
			"18": {MaxPorts: 4},
			"19": {MaxPorts: 8},
			"20": {MaxPorts: 4},
			"21": {MaxPorts: 8},
			"22": {MaxPorts: 4},
			"23": {MaxPorts: 8},
			"24": {MaxPorts: 4},
			"25": {MaxPorts: 8},
			"26": {MaxPorts: 4},
			"27": {MaxPorts: 8},
			"28": {MaxPorts: 4},
			"29": {MaxPorts: 8},
			"30": {MaxPorts: 4},
			"31": {MaxPorts: 8},
			"32": {MaxPorts: 4},
			"33": {MaxPorts: 8},
			"34": {MaxPorts: 4},
			"35": {MaxPorts: 8},
			"36": {MaxPorts: 4},
			"37": {MaxPorts: 8},
			"38": {MaxPorts: 4},
			"39": {MaxPorts: 8},
			"40": {MaxPorts: 4},
			"41": {MaxPorts: 8},
			"42": {MaxPorts: 4},
			"43": {MaxPorts: 8},
			"44": {MaxPorts: 4},
			"45": {MaxPorts: 8},
			"46": {MaxPorts: 4},
			"47": {MaxPorts: 8},
			"48": {MaxPorts: 4},
			"49": {MaxPorts: 8},
			"50": {MaxPorts: 4},
			"51": {MaxPorts: 8},
			"52": {MaxPorts: 4},
			"53": {MaxPorts: 8},
			"54": {MaxPorts: 4},
			"55": {MaxPorts: 8},
			"56": {MaxPorts: 4},
			"57": {MaxPorts: 8},
			"58": {MaxPorts: 4},
			"59": {MaxPorts: 8},
			"60": {MaxPorts: 4},
			"61": {MaxPorts: 8},
			"62": {MaxPorts: 4},
			"63": {MaxPorts: 8},
			"64": {MaxPorts: 4},
		},
	},
}
