apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fabric-dhcp-server.fullname" . }}-data
  labels:
     {{- include "fabric-dhcp-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.pvc.storageClassOverride }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}