//go:build !ignore_autogenerated

// Copyright 2026 Hedgehog
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	gatewayv1alpha1 "go.githedgehog.com/fabric/api/gateway/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPMessageCounters) DeepCopyInto(out *BGPMessageCounters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPMessageCounters.
func (in *BGPMessageCounters) DeepCopy() *BGPMessageCounters {
	if in == nil {
		return nil
	}
	out := new(BGPMessageCounters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPMessages) DeepCopyInto(out *BGPMessages) {
	*out = *in
	out.Received = in.Received
	out.Sent = in.Sent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPMessages.
func (in *BGPMessages) DeepCopy() *BGPMessages {
	if in == nil {
		return nil
	}
	out := new(BGPMessages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPNeighborPrefixes) DeepCopyInto(out *BGPNeighborPrefixes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPNeighborPrefixes.
func (in *BGPNeighborPrefixes) DeepCopy() *BGPNeighborPrefixes {
	if in == nil {
		return nil
	}
	out := new(BGPNeighborPrefixes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPNeighborStatus) DeepCopyInto(out *BGPNeighborStatus) {
	*out = *in
	out.Messages = in.Messages
	out.IPv4UnicastPrefixes = in.IPv4UnicastPrefixes
	out.IPv6UnicastPrefixes = in.IPv6UnicastPrefixes
	out.L2VPNEVPNPrefixes = in.L2VPNEVPNPrefixes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPNeighborStatus.
func (in *BGPNeighborStatus) DeepCopy() *BGPNeighborStatus {
	if in == nil {
		return nil
	}
	out := new(BGPNeighborStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPStatus) DeepCopyInto(out *BGPStatus) {
	*out = *in
	if in.VRFs != nil {
		in, out := &in.VRFs, &out.VRFs
		*out = make(map[string]BGPVRFStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPStatus.
func (in *BGPStatus) DeepCopy() *BGPStatus {
	if in == nil {
		return nil
	}
	out := new(BGPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPVRFStatus) DeepCopyInto(out *BGPVRFStatus) {
	*out = *in
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make(map[string]BGPNeighborStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPVRFStatus.
func (in *BGPVRFStatus) DeepCopy() *BGPVRFStatus {
	if in == nil {
		return nil
	}
	out := new(BGPVRFStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataplaneStatus) DeepCopyInto(out *DataplaneStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataplaneStatus.
func (in *DataplaneStatus) DeepCopy() *DataplaneStatus {
	if in == nil {
		return nil
	}
	out := new(DataplaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRStatus) DeepCopyInto(out *FRRStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRStatus.
func (in *FRRStatus) DeepCopy() *FRRStatus {
	if in == nil {
		return nil
	}
	out := new(FRRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAgent) DeepCopyInto(out *GatewayAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAgent.
func (in *GatewayAgent) DeepCopy() *GatewayAgent {
	if in == nil {
		return nil
	}
	out := new(GatewayAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAgentList) DeepCopyInto(out *GatewayAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAgentList.
func (in *GatewayAgentList) DeepCopy() *GatewayAgentList {
	if in == nil {
		return nil
	}
	out := new(GatewayAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAgentSpec) DeepCopyInto(out *GatewayAgentSpec) {
	*out = *in
	in.Gateway.DeepCopyInto(&out.Gateway)
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make(map[string]VPCInfoData, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Peerings != nil {
		in, out := &in.Peerings, &out.Peerings
		*out = make(map[string]gatewayv1alpha1.PeeringSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make(map[string]GatewayGroupInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Communities != nil {
		in, out := &in.Communities, &out.Communities
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAgentSpec.
func (in *GatewayAgentSpec) DeepCopy() *GatewayAgentSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAgentSpecConfig) DeepCopyInto(out *GatewayAgentSpecConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAgentSpecConfig.
func (in *GatewayAgentSpecConfig) DeepCopy() *GatewayAgentSpecConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayAgentSpecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAgentStatus) DeepCopyInto(out *GatewayAgentStatus) {
	*out = *in
	in.LastAppliedTime.DeepCopyInto(&out.LastAppliedTime)
	in.LastHeartbeat.DeepCopyInto(&out.LastHeartbeat)
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAgentStatus.
func (in *GatewayAgentStatus) DeepCopy() *GatewayAgentStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayGroupInfo) DeepCopyInto(out *GatewayGroupInfo) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]GatewayGroupMember, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayGroupInfo.
func (in *GatewayGroupInfo) DeepCopy() *GatewayGroupInfo {
	if in == nil {
		return nil
	}
	out := new(GatewayGroupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayGroupMember) DeepCopyInto(out *GatewayGroupMember) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayGroupMember.
func (in *GatewayGroupMember) DeepCopy() *GatewayGroupMember {
	if in == nil {
		return nil
	}
	out := new(GatewayGroupMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayState) DeepCopyInto(out *GatewayState) {
	*out = *in
	in.LastCollectedTime.DeepCopyInto(&out.LastCollectedTime)
	out.Dataplane = in.Dataplane
	out.FRR = in.FRR
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make(map[string]VPCStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Peerings != nil {
		in, out := &in.Peerings, &out.Peerings
		*out = make(map[string]PeeringStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.BGP.DeepCopyInto(&out.BGP)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayState.
func (in *GatewayState) DeepCopy() *GatewayState {
	if in == nil {
		return nil
	}
	out := new(GatewayState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeeringStatus) DeepCopyInto(out *PeeringStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeeringStatus.
func (in *PeeringStatus) DeepCopy() *PeeringStatus {
	if in == nil {
		return nil
	}
	out := new(PeeringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCInfoData) DeepCopyInto(out *VPCInfoData) {
	*out = *in
	in.VPCInfoSpec.DeepCopyInto(&out.VPCInfoSpec)
	out.VPCInfoStatus = in.VPCInfoStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCInfoData.
func (in *VPCInfoData) DeepCopy() *VPCInfoData {
	if in == nil {
		return nil
	}
	out := new(VPCInfoData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCStatus) DeepCopyInto(out *VPCStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCStatus.
func (in *VPCStatus) DeepCopy() *VPCStatus {
	if in == nil {
		return nil
	}
	out := new(VPCStatus)
	in.DeepCopyInto(out)
	return out
}
